name: Loan_prediction
channels:
  - defaults

dependencies:
  - python=3.12.4
  - pip<=24.0
  - pip:
      - mlflow==2.16.2
      - cloudpickle==2.2.1
      - numpy==1.26.4
      - scikit-learn==1.4.2
      - pyyaml==6.0.1
      - packaging==23.1
      - scipy==1.13.1
      - pandas==2.2.3
